### ISSUE TITLE
Run a `Session` in a `Transaction`

### ISSUE THREAD

**Issue by mitchellwrosen** [nikita-volkov/hasql-transaction#10]
Would it be possible to export a function allowing one to run a `Session` inside a `Transaction`?

**Comment by mitchellwrosen** [comment]
I've opened #11 in case you want it.

**Comment by nikita-volkov** [comment]
The absence of such interface is intentional. Allowing to lift sessions would open doors for nesting of transactions and IO, which would cause all sorts of bugs.

**Comment by mitchellwrosen** [comment]
Good point!

**Comment by mitchellwrosen** [comment]
Btw, this came up in a context where I actually do know a `Session` is composed only of `Statement`s, so I would like some sort of `unsafeLiftSession` - but agreed that in general this should be prevented.

**Comment by nikita-volkov** [comment]
Why not just define that session as a transaction from the beginning?

**Comment by mitchellwrosen** [comment]
That'll work :)
