### ISSUE TITLE
Need help on how to use transactions

### ISSUE THREAD

**Issue by ChristophP** [nikita-volkov/hasql-transaction#12]
Hi there,
I've been using `hasql` and it's been a great experience so far. Thanks for making it.

However, I am having a hard time trying to use `hasql-transaction`. I couldn't find any examples on how to use it in the official docs or via google.

Would you consider adding some small examples to the Readme or docs?

**Comment by ChristophP** [comment]
Specifically I am talking about how to use transactions with multiple statement (not using `sql` with a string, but combining multiple statements)

**Comment by ChristophP** [comment]
I think I may have found my answer here: https://github.com/nikita-volkov/hasql-transaction/blob/master/conflicts-test/Main/Transactions.hs#L18-L26 .
However, I still think it would be great to have an example in a more prominent place.

**Comment by nikita-volkov** [comment]
I didn't invest into making examples, because I thought the types in the library kinda made it obvious how to use it. However I do believe that it's always better to have examples than not. I will happily accept a PR with such an example.

**Comment by ChristophP** [comment]
Sounds good. I will just open a PR when I get around to it.
