### ISSUE TITLE
MonadThrow instance

### ISSUE THREAD

**Issue by mitchellwrosen** [nikita-volkov/hasql-transaction#18]
Hi, could a MonadThrow instance be added to Transaction?

**Comment by nikita-volkov** [comment]
Hey! What for? It doesn't throw exceptions

**Comment by mitchellwrosen** [comment]
Indeed, and that's great :)

... but for many applications, like boring CRUD apps, often the most ergonomic way to end the handling of a client's request (with a 400, 404, etc) is to short-circuit with an exception, and catch at some top-level handler to translate into a response.

This can be accomplished without a MonadThrow instance, of course, by either returning a Left or using ExceptT to recover short-circuiting syntax, but neither of these are without drawbacks.

**Comment by nikita-volkov** [comment]
I don't quite see how you expect this to be implemented. What I see is switching the error-reporting approach in the whole ecosystem to exceptions yet it doesn't seem like you're asking that. Could you clarify?

**Comment by mitchellwrosen** [comment]
Sure, I'm asking if it would make sense to add a`MonadThrow`instance that would allow users to throw their own exceptions (with `throwM`).

Currently, a transaction may ultimately fail with a `QueryError`, which (in the CRUD example) may ultimately be parsed and translated into a 500 for the client (connectivity issue), or perhaps a 409 conflict (unique constraint violation), etc.

But other times, the application might make a series of successful calls to the database before determining that the input was bad, or something, and we should return a 400 to the client.

Without a `MonadThrow` instance, this type of logic currently would either incur a level of nesting (to return with a Left or proceed with a Right), or an `ExceptT` layer (which doesn't compose that well with non-throwing transactions, as it requires littering `lift`s).

A `MonadThrow` instance would allow users to opt-into using a distinct error-throwing variant at their discretion, which doesn't incur a syntactic indentation nor monad transformer layer, but which does (unfortunately) go untracked in the type system

**Comment by nikita-volkov** [comment]
That would require basically reimplementing the whole error reporting in Hasql to work on exceptions and I don't see anything good in exceptions whatsoever. Even in your case, it sounds like using exceptions would be basically obscuring the logic of your app. The way that I see it is that detecting the status to report to the client is part of the logic of your app. In that case exceptions sounds like a roundabout way of encoding something that could be expressed directly.

**Comment by mitchellwrosen** [comment]
Sounds good, thanks
