### ISSUE TITLE
Ability to trigger an eventual rollback

### ISSUE THREAD

**Issue by begriffs** [nikita-volkov/hasql-transaction#4]
There's a case when my app detects a conflict in the database action it has been asked to do, and I'd like to be able to roll back the results. Here's the current logic:

```haskell
run $ do
  -- perform an update returning *
  rows <- query foo
  -- if rows indicate an undesirable result, roll it back
  when badThings $ sql "ROLLBACK;"
  -- create summary based on the success or failure
  return resultsSummary
```

However the Hasql transaction calls always `COMMIT`, even after my `ROLLBACK`. I could intentionally cause a database error in the code in order to trigger a transaction failure, but then I think it will interrupt my code from creating a custom summary of results.

Is there a way to provide a function in the transaction API to let my code proceed through the transaction without interruption, but ultimately roll back changes at the end?

This relates to https://github.com/begriffs/postgrest/pull/763

**Comment by nikita-volkov** [comment]
So you want to roll the changes back depending on a result of a query, while still producing some output, right? I'm afraid with the current design of the library it's not achievable. 

Have you considered approaching the problem with the `WriteWithoutCommitting` mode though?

**Comment by begriffs** [comment]
Well `WriteWithoutCommitting` is probably too categorical. Most the time we do want to commit, it's just occasionally we'd like to tell the transaction to roll back due to what we learn from the query results.

One workaround is for us to raise a specific postgres exception, which is picked up in the general error handler of the app. Could make the handler recognize and parse that specific exception to generate the right output, but it couples parts of the program that are currently pretty unrelated.

Would it be difficult to add this requested-rollback feature to Hasql, or does it violate some design decision?

**Comment by nikita-volkov** [comment]
I don't think it's be possible to extend this library with such functionality cleanly.

Let's say, for instance, a function `rollback :: Transaction ()` is introduced - what's gonna happen when a query is executed after the rollback? I don't see a way of dealing with that without making the abstraction leak.

Looks like `hasql-transaction` is not fit for your use-case and that it'll be wisest to do transactions manually.

**Comment by begriffs** [comment]
Here is an idea, let me know if you think it's too leaky. Being inside Transaction means that the statements will be bracketed with begin and commit. I'm imagining a function which doesn't change execution of statements inside `run`, but merely changes what happens at the end. Something like

```haskell
results <- run $ do
  -- sql statements etc...

  if badThingHappened
    then do
      condemn  -- new function provided by hasql-transaction
      return situationDetails
    else do
      -- more sql statements etc
      return otherSituationDetails

-- at this point hasql-transaction will either commit or rollback the
-- statements from the previous `run` block depending on whether
-- `condemn` was called.

-- Either way `results` contains information.
```

So the code inside the transaction doesn't get any new control flow, it just has a way to signal adversity to the library to change what happens at the end (since something will happen anyway, ordinarily a commit).

**Comment by nikita-volkov** [comment]
Good idea! I'll accept an according PR. Otherwise I'll explore it a bit later.
